<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise.prototype.then</title>
</head>
<body>
    <script>
        //创建promise对象
        const p = new Promise((resolve,reject)=>{
            setTimeout(()=>{
                // resolve('用户数据');
                reject('用户数据');
            }, 1000);
        });
        const result = p.then(value =>{
        //调用then方法 then方法的返回结果是 Promise对象 ，对象的状态
        //由回调函数的执行结果决定
        //1.如果回调函数中返回的结果是 非Promise 类型的属性,状态为成功，返回值为对象的成功值
        //2.如果返回为promise对象，result结果由返回的promise决定
        //3.抛出错误 状态为失败，值为错误对象的表现形式
            console.log(value);
            return 123;
        }, reason => {
            console.warn(reason);
            //没有返回语句 返回undefined 为非promise类型 ，状态依旧为成功，返回值undefined

            //返回promise
            // return new Promise((resolve,reject)=>{
            //     // resolve('ok');
            //     reject('error')
            // });

            //抛出储物
            throw new Error('出错啦！');
        });

        console.log(p);
        console.log(result);

        //链式调用 解决回调地狱
        new Promise((resolve,reject)=>{
            resolve('ok');
        }).then(value=>{

        }).then(value=>{

        },reason=>{
            
        });
    </script>
    
</body>
</html>